---
attributes: &attributes
  ama-docker-compose:
    version: 1.16.1
    integration:
      workspace: /tmp/ama
      fixed_version:
        version: 1.8.0
      overwrite:
        default_version: 1.8.0
        overwrite_version: 1.10.1

driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  attributes: *attributes

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7.11
  - name: debian-8.6
  - name: centos-6.5
  - name: centos-7.2
  - name: fedora-21
  - name: fedora-22
  - name: fedora-23
  - name: fedora-24
  - name: fedora-25

suites:
  - name: default
    run_list:
      - recipe[ama-docker-compose-integration::default]
    attributes: *attributes
