sudo: required
services:
  - docker
rvm:
  - 2.4
env:
  global:
    KITCHEN_LOCAL_YAML: ".kitchen.travis.yml"
  matrix:
    - PLATFORM_PATTERN=ubuntu
    - PLATFORM_PATTERN=debian
    - PLATFORM_PATTERN=centos
    - PLATFORM_PATTERN=fedora
script:
  - bundle exec kitchen test $PLATFORM_PATTERN
before_install:
  - gem update --system
  - openssl aes-256-cbc -K $encrypted_58eb139a4a99_key -iv $encrypted_58eb139a4a99_iv -in .supermarket_key.encrypted -out .supermarket_key -d
deploy:
  provider: chef-supermarket
  user_id: ama-team
  client_key: .supermarket_key
  cookbook_name: ama-docker-compose
  cookbook_category: Operating Systems & Virtualization
  on:
    condition: '"$PLATFORM_PATTERN" = "ubuntu"'
    tags: true
